### ISSUE TITLE
MOM6 solo config crashes b/c of obsolete runtime flag MIN_Z_DIAG_INTERVAL

### ISSUE THREAD

**Issue by wrongkindofdoctor** [NOAA-GFDL/MOM6#930]
When running the mom6_solo_global_ALE_z experiment using the latest dev/gfdl branch, MOM_obosolete_params  catches the now obsolete runtime flag MIN_Z_DIAG_INTERVAL:

Error message:
```
FATAL from PE     0: MOM_obsolete_params: MIN_Z_DIAG_INTERVAL is an obsolete run
-time flag, and should not be used.
```

Stack trace:
```
Backtrace for this error:
#0  0x277d32f in ???
	at /home/abuild/rpmbuild/BUILD/glibc-2.22/nptl/../sysdeps/unix/sysv/linu
x/x86_64/sigaction.c:0
#1  0x2ac3abb in raise
	at ../sysdeps/unix/sysv/linux/pt-raise.c:36
#2  0x2c9cdc9 in abort
	at /home/abuild/rpmbuild/BUILD/glibc-2.22/stdlib/abort.c:78
#3  0x2ae04f1 in ???
#4  0x2ac3fa8 in ???
#5  0x2ac51d4 in ???
#6  0x1d7404b in __mpp_mod_MOD_mpp_error_basic
	at /lustre/f2/dev/Jessica.Liptak/MOM6_solo_liptak_fork_dev_gfdl/mom6_sol
o_compile/src/shared/mpp/include/mpp_util_mpi.inc:69
#7  0x5204af in __mom_error_handler_MOD_mom_error
	at /lustre/f2/dev/Jessica.Liptak/MOM6_solo_liptak_fork_dev_gfdl/mom6_sol
o_compile/src/mom6/src/MOM6/src/framework/MOM_error_handler.F90:89
#8  0x8af825 in __mom_obsolete_params_MOD_obsolete_real
	at /lustre/f2/dev/Jessica.Liptak/MOM6_solo_liptak_fork_dev_gfdl/mom6_sol
o_compile/src/mom6/src/MOM6/src/diagnostics/MOM_obsolete_params.F90:294
#9  0x8b15a4 in __mom_obsolete_params_MOD_find_obsolete_params
	at /lustre/f2/dev/Jessica.Liptak/MOM6_solo_liptak_fork_dev_gfdl/mom6_sol
o_compile/src/mom6/src/MOM6/src/diagnostics/MOM_obsolete_params.F90:204
#10  0x446802 in __mom_MOD_initialize_mom
	at /lustre/f2/dev/Jessica.Liptak/MOM6_solo_liptak_fork_dev_gfdl/mom6_sol
o_compile/src/mom6/src/MOM6/src/core/MOM.F90:1614
#11  0x40bd4d in mom_main
	at /lustre/f2/dev/Jessica.Liptak/MOM6_solo_liptak_fork_dev_gfdl/mom6_sol
o_compile/src/mom6/src/MOM6/config_src/solo_driver/MOM_driver.F90:315
#12  0x40df9d in main
	at /lustre/f2/dev/Jessica.Liptak/MOM6_solo_liptak_fork_dev_gfdl/mom6_sol
o_compile/src/mom6/src/MOM6/config_src/solo_driver/MOM_driver.F90:27
srun: Received task exit notification for 1 task of step 268442892.0 (status=0x0
086).
```
I will track down and remove the offending parameter, and submit a pull request with the fix unless someone else beats me to it.

**Comment by marshallward** [comment]
This should already be fixed in the MOM6-examples tests, but there probably should have been a little more warning.  Apologies if it's caused any trouble for you.

**Comment by wrongkindofdoctor** [comment]
Thanks, Marshall. I just updated MOM6_examples and that solved the issue.
